// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANtEXdpIveoZFudZykGAc9WOWnQ1bESqk',
    appId: '1:399147824129:web:373e559a1b61b8b3683c00',
    messagingSenderId: '399147824129',
    projectId: 'mygame-203ad',
    authDomain: 'mygame-203ad.firebaseapp.com',
    storageBucket: 'mygame-203ad.firebasestorage.app',
    measurementId: 'G-1EHSFN671E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3P1JU02XMwABgNikd3E4YDhSNe4vbhe4',
    appId: '1:399147824129:android:4e2ce784c9f615d5683c00',
    messagingSenderId: '399147824129',
    projectId: 'mygame-203ad',
    storageBucket: 'mygame-203ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn-n0o42dlmwFZspxY6SXVoXcDMjXxBPg',
    appId: '1:399147824129:ios:fd49eef5b1292b7a683c00',
    messagingSenderId: '399147824129',
    projectId: 'mygame-203ad',
    storageBucket: 'mygame-203ad.firebasestorage.app',
    iosBundleId: 'com.example.myGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn-n0o42dlmwFZspxY6SXVoXcDMjXxBPg',
    appId: '1:399147824129:ios:fd49eef5b1292b7a683c00',
    messagingSenderId: '399147824129',
    projectId: 'mygame-203ad',
    storageBucket: 'mygame-203ad.firebasestorage.app',
    iosBundleId: 'com.example.myGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANtEXdpIveoZFudZykGAc9WOWnQ1bESqk',
    appId: '1:399147824129:web:a089876ed39c0af3683c00',
    messagingSenderId: '399147824129',
    projectId: 'mygame-203ad',
    authDomain: 'mygame-203ad.firebaseapp.com',
    storageBucket: 'mygame-203ad.firebasestorage.app',
    measurementId: 'G-ER2DJ96VHP',
  );

}